name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: nasm
      run: brew install nasm 

    - name: x86_64-elf-gcc
      run: brew install x86_64-elf-gcc

    - name: setup
      run: ./setup.sh

    - name: build
      run: ./build.sh

  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: install nasm
      run: sudo apt install nasm

    - name: setup
      run: ./setup.sh

    - name: build
      run: ./build.sh

  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: choco install nasm mingw

    - name: setup
      run: ./setup.sh

    - name: build
      run: ./build.sh

      
